### ISSUE TITLE
Add custom ignore configuration to copyFiles for project files (like gitignore)

### ISSUE THREAD

**Issue by muhammedikinci** [muhammedikinci/pin#7]
I want to add file and folder ignore support with Golang regexp like the below example;

sample configuration yaml
```yaml
run:
  image: node:current-alpine3.15
  copyFiles: true
  soloExecution: true
  port:
    - 8080:8080
  copyIgnore:
    - server.js
    - props
    - README.md
    - helper/.*/.py
```

actual folder structure in project
```yaml
index.js
server.js
README.md
helper:
    - test.py
    - mock
        test2.py
    - api:
        index.js
    - props:
        index.js
```

expected folder structure in container
```yaml
index.js
helper:
    - mock (empty)
    - api:
        index.js
```
