### ISSUE TITLE
Support concurrent jobs

### ISSUE THREAD

**Issue by muhammedikinci** [muhammedikinci/pin#9]
I will add the `parallel` field to the stage for concurrent support. 

```yaml
parallelJob:
  image: node:current-alpine3.15
  copyFiles: true
  soloExecution: true
  parallel: true
  script:
    - ls -a
```
